### ISSUE TITLE
Update npm package

### ISSUE THREAD

**Issue by pilotak** [miroRucka/bh1750#2]
Thanks for updating to V0.12, could you please update npm package too? so i don't have to download it from Git but NPM

**Comment by miroRucka** [comment]
thanks for your update. I publish new version 0.0.3 on npm.

**Comment by rzr** [comment]
npm is still oudated
please also tag current master it will appear at:
https://github.com/miroRucka/bh1750/releases

**Comment by rzr** [comment]
Please run commands I shared at:
https://github.com/miroRucka/bh1750/pull/19


Or If it helps I can automate publishing to npm.org using travis

an other option would be to fork the project into this org:

https://www.npmjs.com/org/abandonware

but I would prefer to avoid and stay as it is...

**Comment by rzr** [comment]
Ping

**Comment by jhoughjr** [comment]
bump
