### ISSUE TITLE
Support Node 10

### ISSUE THREAD

**Issue by rzr** [miroRucka/bh1750#22]
It looks like i2c module is no more maintained maybe we can use an other i2c implementation ?

Relate-to: https://github.com/kelly/node-i2c/issues/90
Relate-to: https://github.com/kelly/node-i2c/issues/91

**Comment by shidevil** [comment]
Will it support node 12? with abandonware i2c.

**Comment by rzr** [comment]
I think so, I would make sense to merge it , then I will rebase and check

meanwhile use the abandonware version:

https://github.com/abandonware/bh1750

May I suggest also to try:
https://github.com/rzr/generic-sensors-lite

**Comment by shidevil** [comment]
Sadly i tried abandonware i2c and it doesn't compile with node 12. i2c failed to compile.

**Comment by rzr** [comment]
Then please file bug in 
https://github.com/kelly/node-i2c/issues
or share patches to:
https://github.com/abandonware/node-i2c

**Comment by shidevil** [comment]
@rzr Will file a bug there. Thanks

**Comment by rzr** [comment]
Relate-to: https://github.com/kelly/node-i2c/issues/98

**Comment by rzr** [comment]
I think this issue can be solved master branch has my changes in

Meanwhile it is released you can use:

https://www.npmjs.com/package/@abandonware/bh1750/v/0.0.7-2
